---

- name: "[WORDPRESS] - check if Wordpress is already present"
  stat:
    path: "/var/www/wordpress/"
  register: check_wordpress

- name: "[WORDPRESS] - download tar.gz"
  unarchive:
    src: "{{ wordpress_source }}"
    dest: "/var/www/"
    remote_src: yes
  when: check_wordpress.stat.exists == False

- name: "[WORDPRESS] - remove index.html"
  file:
    path: "/var/www/html/index.html"
    state: absent

- name: "[WORDPRESS] - exist wp-config-sample.php"
  stat:
    path: "/var/www/wordpress/wp-config-sample.php"
  register: check_sample

- name: "[WORDPRESS] - rename wp-config-sample.php"
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  when: check_sample.stat.exists == True

- name: "[WORDPRESS] - config wp-config.php"
  lineinfile:
    dest: "/var/www/wordpress/wp-config.php"
    regexp: "{{ item.search }}"
    line: "{{ item.new }}"
    backrefs: yes
  with_items:
    - {'search': '^(.*)database_name_here(.*)$', 'new': '\1{{ mysql_db }}\2'}
    - {'search': '^(.*)username_here(.*)$', 'new': '\1{{ mysql_user }}\2'}
    - {'search': '^(.*)password_here(.*)$', 'new': '\1{{ mysql_password }}\2'}

- name: "[WORDPRESS] - modif racine apache /var/www/html to /var/www/wordpress"
  lineinfile:
    dest: "{{ item  }}"
    regexp: "/var/www/html"
    line: "DocumentRoot /var/www/wordpress"
    backrefs: yes
  with_items:
    - "/etc/apache2/sites-available/default-ssl.conf"
    - "/etc/apache2/sites-available/000-default.conf"
    - "/etc/apache2/sites-enabled/000-default.conf"

