- name: "[WORDPRESS] - update cache"
  apt:
    update_cache: yes
  become: yes

- name: "[WORDPRESS] - install LAMP"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ package_name }}"

- name: "[WORDPRESS] - start services"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - apache2
    - mysql

