---
# tasks file for wordpress
#
- name: "[WORDPRESS] - install package + start des services"
  include: install_packages.yml

- name: "[WORDPRESS] - install db"
  include: install_db.yml

- name: "[WORDPRESS] - install Wordpress"
  include: install_wp.yml

